// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemgvasU0UDyaVA35RcVXOrhvaDkHIXPc',
    appId: '1:457582385653:android:d24d18de7942bd4e93e8bc',
    messagingSenderId: '457582385653',
    projectId: 'grocery-app-34eeb',
    storageBucket: 'grocery-app-34eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZVPiYuZPqgaK8x_0m56yhni4JktJ0ek',
    appId: '1:457582385653:ios:7944cc8c8fecae6293e8bc',
    messagingSenderId: '457582385653',
    projectId: 'grocery-app-34eeb',
    storageBucket: 'grocery-app-34eeb.firebasestorage.app',
    androidClientId: '457582385653-eql7cdel2fptkmbt9rvaoenvcaf2b33b.apps.googleusercontent.com',
    iosClientId: '457582385653-hb2o65r9tsgfpechh1r8hrpvv026pni1.apps.googleusercontent.com',
    iosBundleId: 'com.example.blinkitClone',
  );

}